# Generated by Django 5.1.5 on 2025-02-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('calorie_intake', models.FloatField(blank=True, null=True)),
                ('protein_intake', models.FloatField(blank=True, null=True)),
                ('calories_consumed', models.FloatField(default=0.0)),
                ('protein_consumed', models.FloatField(default=0.0)),
                ('weight_history', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
