# Generated by Django 5.1.5 on 2025-02-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_weight',
            field=models.FloatField(default=45),
            preserve_default=False,
        ),
    ]
