# Generated by Django 5.1.5 on 2025-02-09 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_current_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_body_shape',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_weight',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='workout_level',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
